#!/usr/bin/env node

var fs = require( 'fs' ),
    exec = require('child_process').exec,
    env = process.env;

var DATA = env.OPENSHIFT_DATA_DIR,
    REPO = env.OPENSHIFT_REPO_DIR;

fs.existsSync( REPO + 'server/database.production' ) || fs.linkSync( DATA + 'database.production', REPO + 'server/database.production' );
fs.existsSync( REPO + 'server/database.development' ) || fs.linkSync( DATA + 'database.development', REPO + 'server/database.development' );
fs.existsSync( REPO + 'server/email.json' ) || fs.linkSync( DATA + 'email.json', REPO + 'server/email.json' );

exec( 'cd ' + REPO, function( e ){
    e && console.log( e );

    exec( 'HOME=/tmp bower install', function ( e ) {

        console.log( e );
        fs.renameSync( REPO + '.openshift/action_hooks/bower_components', REPO + 'bower_components' );

    } );
} )
